/**
 * War Roguelike — content: items
 */
(function (global) {
    "use strict";
    global.WarDataParts = global.WarDataParts || {};
    const ARTIFACTS = [
        { id: "iron_shield", name: "鐵盾", rarity: "common", desc: "全隊防禦 +6", effect: {"defAll":6} },
        { id: "sharp_blade", name: "鋒利之刃", rarity: "common", desc: "全隊攻擊 +8", effect: {"atkAll":8} },
        { id: "swift_boots", name: "疾風靴", rarity: "common", desc: "攻速 +19%", effect: {"spdMult":1.185} },
        { id: "healing_herb", name: "療傷草", rarity: "common", desc: "戰後額外 +30 金幣", effect: {"healAfter":30} },
        { id: "lucky_coin", name: "幸運幣", rarity: "common", desc: "金幣獎勵 +37%", effect: {"goldMult":1.37} },
        { id: "thick_armor", name: "厚甲", rarity: "common", desc: "[坦克] HP +80", effect: {"tag":"tank","hp":80} },
        { id: "hunter_bow", name: "獵人弓", rarity: "common", desc: "[射手] 攻擊 +16", effect: {"tag":"ranger","atk":16} },
        { id: "mana_crystal", name: "魔力水晶", rarity: "common", desc: "[法師] 攻擊 +20", effect: {"tag":"caster","atk":20} },
        { id: "iron_glaive", name: "鐵刃戟", rarity: "common", desc: "[近戰] 攻擊 +12", effect: {"tag":"melee","atk":12} },
        { id: "war_banner", name: "戰旗", rarity: "uncommon", desc: "全隊攻擊 +16", effect: {"atkAll":16} },
        { id: "fortress_wall", name: "堡壘之牆", rarity: "uncommon", desc: "全隊 HP +70", effect: {"hpAll":70} },
        { id: "vampire_fang", name: "吸血獠牙", rarity: "uncommon", desc: "吸血 17%", effect: {"lifesteal":0.17} },
        { id: "thorns_mail", name: "荊棘甲", rarity: "uncommon", desc: "反傷 31%", effect: {"thorns":0.306} },
        { id: "scout_lens", name: "偵察鏡", rarity: "uncommon", desc: "地圖顯示下一層房間類型", effect: {"revealNext":true} },
        { id: "merchants_ring", name: "商人戒指", rarity: "uncommon", desc: "商店價格 -43%", effect: {"shopDiscount":0.425} },
        { id: "scholar_tome", name: "學識寶典", rarity: "rare", desc: "戰鬥經驗 ×2.388，並額外 +2 經驗", effect: {"expMult":2.388,"expBonus":2} },
        { id: "eagle_eye", name: "鷹眼", rarity: "uncommon", desc: "[射手] 暴擊 +31%", effect: {"tag":"ranger","critChance":0.306} },
        { id: "longshot_lens", name: "遠射鏡", rarity: "uncommon", desc: "[遠程] 攻擊 +12；技能冷卻 -19%；射程 +40", effect: {"tag":"ranged","atk":12,"attackRange":40,"skillCdMult":0.815} },
        { id: "wind_string", name: "風弦", rarity: "common", desc: "[射手] 射程 +36", effect: {"tag":"ranger","attackRange":36} },
        { id: "focusing_crystal", name: "聚能晶體", rarity: "common", desc: "[奧術] 射程 +30", effect: {"tag":"arcane","attackRange":30} },
        { id: "phoenix_feather", name: "鳳凰羽毛", rarity: "rare", desc: "戰鬥中首次陣亡時復活 60% HP", effect: {"revive":0.595} },
        { id: "revenant_lantern", name: "復生提燈", rarity: "epic", desc: "每場戰鬥結束後，自動復活 2 名本場陣亡單位", effect: {"postBattleRevive":2} },
        { id: "dragon_scale", name: "龍鱗", rarity: "rare", desc: "全隊防禦 +24", effect: {"defAll":24} },
        { id: "storm_hammer", name: "風暴之錘", rarity: "rare", desc: "[戰士] 攻擊 +44", effect: {"tag":"warrior","atk":44} },
        { id: "shadow_cloak", name: "暗影斗篷", rarity: "rare", desc: "[暗影] 攻速 +46%；技能冷卻 -28%", effect: {"tag":"shadow","spdMult":1.463,"skillCdMult":0.722} },
        { id: "holy_relic", name: "聖物", rarity: "rare", desc: "[神聖] 攻擊 +12；治療量 +111%", effect: {"tag":"holy","healBoost":2.11,"atk":12} },
        { id: "gold_magnet", name: "吸金磁石", rarity: "rare", desc: "金幣獎勵 +93%", effect: {"goldMult":1.925} },
        { id: "healing_spring", name: "治療之泉", rarity: "rare", desc: "戰後額外 +80 金幣", effect: {"healAfter":80} },
        { id: "iron_will", name: "鋼鐵意志", rarity: "rare", desc: "全隊 HP +60", effect: {"commanderHp":60} },
        { id: "sacred_seal", name: "聖印", rarity: "rare", desc: "[神聖] 防禦 +12；技能威力 +55%", effect: {"tag":"holy","skillPower":1.555,"def":12} },
        { id: "hawk_plume", name: "鷹羽", rarity: "rare", desc: "[遠程] 射程 +70", effect: {"tag":"ranged","attackRange":70} },
        { id: "sniper_crest", name: "狙擊徽記", rarity: "rare", desc: "[射手] 攻擊 +16；射程 +60", effect: {"tag":"ranger","attackRange":60,"atk":16} },
        { id: "crown_of_kings", name: "王者之冠", rarity: "epic", desc: "全隊攻擊 +28；全隊 HP +110", effect: {"atkAll":28,"hpAll":110} },
        { id: "time_sand", name: "時之沙", rarity: "epic", desc: "技能冷卻 -46%", effect: {"skillCdMult":0.538} },
        { id: "berserker_axe", name: "狂戰斧", rarity: "epic", desc: "HP 低於 50% 時攻擊 +68%", effect: {"lowHpAtk":0.68} },
        { id: "arcane_tome", name: "奧術典籍", rarity: "epic", desc: "[奧術] 技能威力 +102%", effect: {"tag":"arcane","skillPower":2.018} },
        { id: "titans_belt", name: "泰坦腰帶", rarity: "epic", desc: "[坦克] HP +220", effect: {"tag":"tank","hp":220} },
        { id: "war_horn", name: "戰爭號角", rarity: "epic", desc: "開場全隊獲得護盾 160", effect: {"startShield":160} },
        { id: "wild_totem", name: "野獸圖騰", rarity: "epic", desc: "[野獸] 攻擊 +28；HP +100；技能威力 +46%", effect: {"tag":"beast","hp":100,"atk":28,"skillPower":1.463} },
        { id: "flame_core", name: "焰心", rarity: "epic", desc: "[火焰] 攻擊 +20；技能威力 +74%", effect: {"tag":"fire","skillPower":1.74,"atk":20} },
        { id: "horizon_lens", name: "地平線鏡", rarity: "epic", desc: "[遠程] 攻擊 +12；射程 +100", effect: {"tag":"ranged","attackRange":100,"atk":12} },
        { id: "summon_charm", name: "喚靈符", rarity: "common", desc: "[召喚] 技能冷卻 -28%", effect: {"tag":"summon","skillCdMult":0.722} },
        { id: "binder_ring", name: "縛靈戒", rarity: "uncommon", desc: "[召喚] 召喚上限 +2", effect: {"tag":"summon","summonMax":2} },
        { id: "spirit_horn", name: "靈角", rarity: "rare", desc: "[召喚] 技能冷卻 -37%；召喚上限 +2", effect: {"tag":"summon","skillCdMult":0.63,"summonMax":2} },
        { id: "pack_totem", name: "群召圖騰", rarity: "rare", desc: "[召喚] 攻擊 +16；HP +70", effect: {"tag":"summon","hp":70,"atk":16} },
        { id: "legion_sigil", name: "軍團印記", rarity: "epic", desc: "[召喚] 技能冷卻 -46%；召喚上限 +4", effect: {"tag":"summon","summonMax":4,"skillCdMult":0.538} },
        { id: "void_orb", name: "虛空寶珠", rarity: "legendary", desc: "全隊攻擊 +40；全隊防禦 +28", effect: {"atkAll":40,"defAll":28} },
        { id: "seal_of_eternity", name: "永恆封印", rarity: "legendary", desc: "獲得唯一單位「永恆守衛」；全隊防禦 +12", effect: {"defAll":12}, grant: {"unit":"eternal_warden"} },
        { id: "void_whisper", name: "虛空低語", rarity: "legendary", desc: "獲得唯一單位「虛空潛行者」；[暗影] 攻速 +19%", effect: {"tag":"shadow","spdMult":1.185}, grant: {"unit":"void_stalker"} },
        { id: "chronos_eye", name: "時序之眼", rarity: "legendary", desc: "獲得唯一單位「時序法師」；技能冷卻 -19%", effect: {"skillCdMult":0.815}, grant: {"unit":"chronomancer"} },
        { id: "tablet_of_dominion", name: "霸權石板", rarity: "legendary", desc: "獲得唯一能力「霸權」；全隊攻擊 +16", effect: {"atkAll":16}, grant: {"ability":"dominion"} },
        { id: "soul_oath_scroll", name: "魂契卷軸", rarity: "legendary", desc: "獲得唯一能力「魂契」；全隊 HP +50", effect: {"hpAll":50}, grant: {"ability":"soul_bond"} },
        { id: "last_stand_banner", name: "背水旗", rarity: "legendary", desc: "獲得唯一能力「背水一戰」；HP 低於 50% 時攻擊 +26%", effect: {"lowHpAtk":0.255}, grant: {"ability":"last_stand"} },
        { id: "volley_pact", name: "連射誓約", rarity: "epic", cursed: true, desc: "【詛咒】僅[遠程]能戰鬥；[遠程] 攻擊 +56；射程 +40；普攻變為 8 連射", effect: {"onlyFightTag":"ranged","tag":"ranged","multishot":8,"atk":56,"attackRange":40} },
        { id: "iron_oath", name: "鐵血誓約", rarity: "epic", cursed: true, desc: "【詛咒】僅[近戰]能戰鬥；[近戰] 攻擊 +64；防禦 +36；HP +280", effect: {"onlyFightTag":"melee","tag":"melee","hp":280,"atk":64,"def":36} },
        { id: "mute_grimoire", name: "緘默魔典", rarity: "epic", cursed: true, desc: "【詛咒】全隊無法施放技能；全隊攻擊 +96、攻速 +74%、暴擊 +20%", effect: {"noSkills":true,"atkAll":96,"spdMult":1.74,"critChance":0.204} },
        { id: "glass_heart", name: "玻璃之心", rarity: "rare", cursed: true, desc: "【詛咒】全隊攻擊 ×3.035；HP ×0.168，受傷 +93%", effect: {"atkMult":3.035,"hpMult":0.168,"dmgTakenMult":1.925} },
        { id: "blood_ledger", name: "血帳", rarity: "rare", cursed: true, desc: "【詛咒】全隊攻擊 +56；吸血 68%；HP ×0.353", effect: {"lifesteal":0.68,"atkAll":56,"hpMult":0.353} },
        { id: "gilded_curse", name: "鍍金詛咒", rarity: "rare", cursed: true, desc: "【詛咒】金幣獎勵 +370%；戰後 +50 金；攻擊 ×0.445", effect: {"goldMult":4.7,"goldAfter":50,"atkMult":0.445} },
        { id: "shadow_bargain", name: "暗影交易", rarity: "legendary", cursed: true, desc: "【詛咒】僅[暗影]能戰鬥；[暗影] 攻擊 +70；攻速 +111%；技能冷卻 -74%；暴擊 +26%", effect: {"onlyFightTag":"shadow","tag":"shadow","spdMult":2.11,"skillCdMult":0.26,"atk":70,"critChance":0.255} },
        { id: "ember_oil", name: "燃焰油", rarity: "uncommon", desc: "普攻 31% 附加燃燒（最大生命 4.0%/秒）", effect: {"onHit":{"type":"burn","chance":0.308,"duration":3.5,"pct":0.0405}} },
        { id: "venom_vial", name: "劇毒瓶", rarity: "rare", desc: "普攻 39% 附加中毒（可疊層）", effect: {"onHit":{"type":"poison","chance":0.392,"duration":5.2,"dps":20}} },
        { id: "frost_brand", name: "霜印刃", rarity: "rare", desc: "普攻 35% 附加凍結", effect: {"onHit":{"type":"freeze","chance":0.35,"duration":2.1,"slow":0.22}} },
        { id: "plague_dagger", name: "瘟疫匕首", rarity: "epic", desc: "[刺客] 攻擊 +20；普攻 63% 附加中毒（可疊層）", effect: {"tag":"assassin","atk":20,"onHit":{"type":"poison","chance":0.63,"duration":5.8,"dps":24}} },
        { id: "cinder_arrows", name: "燼矢", rarity: "epic", desc: "[遠程] 攻擊 +16；普攻 49% 附加燃燒（最大生命 5.4%/秒）", effect: {"tag":"ranged","atk":16,"onHit":{"type":"burn","chance":0.49,"duration":3.7,"pct":0.054}} },
        { id: "blood_edge", name: "血刃", rarity: "rare", desc: "[近戰] 攻擊 +12；普攻 56% 附加流血（可疊層）", effect: {"tag":"melee","atk":12,"onHit":{"type":"bleed","chance":0.56,"duration":4.6,"dps":10}} },
        { id: "storm_capacitor", name: "雷霆電容", rarity: "epic", desc: "[機械] 攻擊 +20；普攻 49% 附加感電", effect: {"tag":"mechanical","atk":20,"onHit":{"type":"shock","chance":0.49,"duration":3.5,"dps":20}} },
        { id: "hex_charm", name: "虛弱咒符", rarity: "uncommon", desc: "普攻 42% 附加虛弱", effect: {"onHit":{"type":"weaken","chance":0.42,"duration":4,"atkMult":0.538}} },
        { id: "ruin_seal", name: "崩毀印記", rarity: "rare", desc: "普攻 35% 附加易傷", effect: {"onHit":{"type":"vulnerable","chance":0.35,"duration":4,"takenMult":1.518}} },
        { id: "aegis_crest", name: "盾衛紋章", rarity: "uncommon", desc: "【盾衛】專屬；防禦 +16；HP +110；招募／獎勵出現率大幅提升", effect: {"unit":"shieldbearer","hp":110,"def":16,"findWeight":3.5} },
        { id: "knight_oath", name: "騎士誓約", rarity: "uncommon", desc: "【騎士】專屬；攻擊 +24；HP +70；招募／獎勵出現率大幅提升", effect: {"unit":"knight","atk":24,"hp":70,"findWeight":3.5} },
        { id: "berserker_totem", name: "狂戰圖騰", rarity: "uncommon", desc: "【狂戰士】專屬；攻擊 +32；攻速 +22%；招募／獎勵出現率大幅提升", effect: {"unit":"berserker","atk":32,"spdMult":1.222,"findWeight":3.5} },
        { id: "hunter_mark", name: "獵手印記", rarity: "uncommon", desc: "【弓箭手】專屬；攻擊 +24；射程 +50；招募／獎勵出現率大幅提升", effect: {"unit":"archer","atk":24,"attackRange":50,"findWeight":3.5} },
        { id: "bolt_quiver", name: "穿甲箭袋", rarity: "uncommon", desc: "【弩手】專屬；攻擊 +20；射程 +60；招募／獎勵出現率大幅提升", effect: {"unit":"crossbowman","atk":20,"attackRange":60,"findWeight":3.5} },
        { id: "arcane_focus", name: "奧術焦點", rarity: "uncommon", desc: "【法師】專屬；攻擊 +28；技能威力 +46%；招募／獎勵出現率大幅提升", effect: {"unit":"mage","atk":28,"skillPower":1.463,"findWeight":3.5} },
        { id: "sacred_rosary", name: "聖光念珠", rarity: "uncommon", desc: "【牧師】專屬；HP +60；治療量 +74%；招募／獎勵出現率大幅提升", effect: {"unit":"priest","healBoost":1.74,"hp":60,"findWeight":3.5} },
        { id: "shadow_contract", name: "暗影契約", rarity: "rare", desc: "【刺客】專屬；攻擊 +28；暴擊 +20%；招募／獎勵出現率大幅提升", effect: {"unit":"assassin","atk":28,"critChance":0.204,"findWeight":3.7} },
        { id: "golem_blueprint", name: "傀儡藍圖", rarity: "rare", desc: "【工程師】專屬；技能冷卻 -28%；召喚上限 +2；招募／獎勵出現率大幅提升", effect: {"unit":"engineer","summonMax":2,"skillCdMult":0.722,"findWeight":3.7} },
        { id: "glacier_tome", name: "冰河魔典", rarity: "rare", desc: "【冰法師】專屬；攻擊 +24；技能威力 +55%；招募／獎勵出現率大幅提升", effect: {"unit":"frost_mage","atk":24,"skillPower":1.555,"findWeight":3.7} },
        { id: "bone_phylactery", name: "骨製命匣", rarity: "rare", desc: "【死靈法師】專屬；技能威力 +46%；召喚上限 +2；招募／獎勵出現率大幅提升", effect: {"unit":"necromancer","summonMax":2,"skillPower":1.463,"findWeight":3.7} },
        { id: "beast_whistle", name: "馴獸哨", rarity: "rare", desc: "【馴獸師】專屬；HP +80；召喚上限 +2；招募／獎勵出現率大幅提升", effect: {"unit":"beastmaster","summonMax":2,"hp":80,"findWeight":3.7} },
        { id: "dragon_saddle", name: "龍鞍", rarity: "epic", desc: "【龍騎士】專屬；攻擊 +36；HP +120；招募／獎勵出現率大幅提升", effect: {"unit":"dragon_rider","atk":36,"hp":120,"findWeight":4} },
        { id: "paladin_relic", name: "聖騎聖物", rarity: "rare", desc: "【聖騎士】專屬；攻擊 +24；防禦 +20；HP +90；招募／獎勵出現率大幅提升", effect: {"unit":"paladin","atk":24,"def":20,"hp":90,"findWeight":3.7} },
        { id: "archmage_staff", name: "大法師杖", rarity: "epic", desc: "【大法師】專屬；攻擊 +32；技能冷卻 -28%；技能威力 +74%；招募／獎勵出現率大幅提升", effect: {"unit":"archmage","atk":32,"skillPower":1.74,"skillCdMult":0.722,"findWeight":4} },
        { id: "sentinel_plaque", name: "哨衛銘牌", rarity: "uncommon", desc: "【哨衛】專屬；防禦 +14；HP +100；招募／獎勵出現率大幅提升", effect: {"unit":"sentinel","hp":100,"def":14,"findWeight":3.5} },
        { id: "cavalier_lance", name: "槍騎長矛", rarity: "uncommon", desc: "【槍騎兵】專屬；攻擊 +24；攻速 +19%；招募／獎勵出現率大幅提升", effect: {"unit":"cavalier","atk":24,"spdMult":1.185,"findWeight":3.5} },
        { id: "marksman_scope", name: "神射瞄準鏡", rarity: "uncommon", desc: "【神射手】專屬；攻擊 +24；射程 +60；招募／獎勵出現率大幅提升", effect: {"unit":"marksman","atk":24,"attackRange":60,"findWeight":3.5} },
        { id: "cleric_chalice", name: "祭司聖杯", rarity: "uncommon", desc: "【祭司】專屬；HP +50；治療量 +65%；招募／獎勵出現率大幅提升", effect: {"unit":"cleric","healBoost":1.648,"hp":50,"findWeight":3.5} },
        { id: "warpriest_hammer", name: "戰祭聖錘", rarity: "rare", desc: "【戰祭司】專屬；攻擊 +20；防禦 +16；HP +70；招募／獎勵出現率大幅提升", effect: {"unit":"warpriest","atk":20,"def":16,"hp":70,"findWeight":3.7} },
        { id: "shadowblade_veil", name: "影刃面紗", rarity: "uncommon", desc: "【影刃】專屬；攻擊 +24；暴擊 +17%；招募／獎勵出現率大幅提升", effect: {"unit":"shadowblade","atk":24,"critChance":0.17,"findWeight":3.5} },
        { id: "huntress_fang", name: "女獵手牙飾", rarity: "rare", desc: "【女獵手】專屬；攻擊 +28；射程 +30；招募／獎勵出現率大幅提升", effect: {"unit":"huntress","atk":28,"attackRange":30,"findWeight":3.7} },
        { id: "reaver_chain", name: "掠奪鎖鏈", rarity: "rare", desc: "【掠奪者】專屬；攻擊 +32；攻速 +22%；招募／獎勵出現率大幅提升", effect: {"unit":"reaver","atk":32,"spdMult":1.222,"findWeight":3.7} },
        { id: "blood_reaver_mask", name: "血怒面具", rarity: "uncommon", desc: "【血怒蠻兵】專屬；攻擊 +28；HP +60；招募／獎勵出現率大幅提升", effect: {"unit":"blood_reaver","atk":28,"hp":60,"findWeight":3.5} },
        { id: "siege_blueprints", name: "要塞炮圖", rarity: "uncommon", desc: "【要塞炮手】專屬；攻擊 +20；射程 +50；招募／獎勵出現率大幅提升", effect: {"unit":"siege_gunner","atk":20,"attackRange":50,"findWeight":3.5} },
        { id: "automaton_core", name: "機兵核心", rarity: "rare", desc: "【自動機兵】專屬；防禦 +20；HP +110；招募／獎勵出現率大幅提升", effect: {"unit":"automaton","hp":110,"def":20,"findWeight":3.7} },
        { id: "flame_adept_censer", name: "焰徒香爐", rarity: "uncommon", desc: "【焰徒】專屬；攻擊 +24；技能威力 +37%；招募／獎勵出現率大幅提升", effect: {"unit":"flame_adept","atk":24,"skillPower":1.37,"findWeight":3.5} },
        { id: "ash_witch_grimoire", name: "灰燼魔典", rarity: "rare", desc: "【灰燼女巫】專屬；攻擊 +28；技能威力 +55%；招募／獎勵出現率大幅提升", effect: {"unit":"ash_witch","atk":28,"skillPower":1.555,"findWeight":3.7} },
        { id: "wolf_knight_banner", name: "狼騎旗", rarity: "uncommon", desc: "【狼騎士】專屬；攻擊 +24；HP +70；招募／獎勵出現率大幅提升", effect: {"unit":"wolf_knight","atk":24,"hp":70,"findWeight":3.5} },
        { id: "occultist_sigil", name: "秘術符印", rarity: "rare", desc: "【秘術師】專屬；技能威力 +37%；召喚上限 +2；招募／獎勵出現率大幅提升", effect: {"unit":"occultist","summonMax":2,"skillPower":1.37,"findWeight":3.7} },
        { id: "colossus_plate", name: "巨像鎧片", rarity: "epic", desc: "【鐵巨像】專屬；防禦 +24；HP +160；招募／獎勵出現率大幅提升", effect: {"unit":"iron_colossus","hp":160,"def":24,"findWeight":4} },
        { id: "storm_rider_reins", name: "風暴韁繩", rarity: "epic", desc: "【風暴騎士】專屬；攻擊 +32；攻速 +28%；招募／獎勵出現率大幅提升", effect: {"unit":"storm_rider","atk":32,"spdMult":1.277,"findWeight":4} }
    ];

    const ABILITIES = [
        { id: "vitality", name: "體魄強化", rarity: "common", desc: "全隊 HP +5", effect: {"commanderHp":5} },
        { id: "sharpened_weapons", name: "武器打磨", rarity: "common", desc: "全隊攻擊 +1.5", effect: {"atkAll":2} },
        { id: "reinforced_armor", name: "強化護甲", rarity: "common", desc: "全隊防禦 +1.5", effect: {"defAll":2} },
        { id: "field_medic", name: "戰地醫療", rarity: "common", desc: "戰後額外 +7.5 金幣", effect: {"healAfter":8} },
        { id: "formation_mastery", name: "陣型精通", rarity: "common", desc: "攻速 +3%", effect: {"spdMult":1.028} },
        { id: "gold_rush", name: "淘金熱", rarity: "uncommon", desc: "金幣獎勵 +10%", effect: {"goldMult":1.105} },
        { id: "veteran_training", name: "老兵訓練", rarity: "uncommon", desc: "全隊 HP +11", effect: {"hpAll":11} },
        { id: "quick_strike", name: "迅捷打擊", rarity: "uncommon", desc: "攻速 +4%", effect: {"spdMult":1.042} },
        { id: "trap_sense", name: "陷阱感知", rarity: "uncommon", desc: "陷阱金幣損失 -23%", effect: {"trapReduce":0.225} },
        { id: "treasure_hunter", name: "寶藏獵人", rarity: "uncommon", desc: "寶藏金幣 +21%", effect: {"treasureMult":1.21} },
        { id: "arcane_study", name: "奧術研習", rarity: "rare", desc: "[奧術] 攻擊 +6", effect: {"tag":"arcane","atk":6} },
        { id: "ranger_focus", name: "射手專注", rarity: "rare", desc: "[射手] 攻擊 +6", effect: {"tag":"ranger","atk":6} },
        { id: "iron_fortress", name: "鋼鐵堡壘", rarity: "rare", desc: "[坦克] HP +26", effect: {"tag":"tank","hp":26} },
        { id: "melee_drill", name: "近戰操練", rarity: "rare", desc: "[近戰] 攻擊 +4.5；防禦 +1.5", effect: {"tag":"melee","atk":5,"def":2} },
        { id: "holy_discipline", name: "聖光戒律", rarity: "rare", desc: "[神聖] HP +21；治療量 +18%", effect: {"tag":"holy","hp":21,"healBoost":1.175} },
        { id: "shadow_arts", name: "影術", rarity: "rare", desc: "[暗影] 攻擊 +7.5；攻速 +8%", effect: {"tag":"shadow","atk":8,"spdMult":1.084} },
        { id: "beast_bond", name: "獸語連結", rarity: "rare", desc: "[野獸] 攻擊 +6；HP +23", effect: {"tag":"beast","hp":23,"atk":6} },
        { id: "fire_doctrine", name: "焰術教義", rarity: "rare", desc: "[火焰] 攻擊 +6；技能威力 +14%", effect: {"tag":"fire","atk":6,"skillPower":1.14} },
        { id: "summon_lore", name: "喚靈學", rarity: "rare", desc: "[召喚] 技能冷卻 -8%；召喚上限 +0.8", effect: {"tag":"summon","skillCdMult":0.916,"summonMax":1} },
        { id: "cavalry_charge", name: "騎兵衝鋒", rarity: "uncommon", desc: "[騎兵] 攻擊 +5.3；攻速 +6%；移速 +14%", effect: {"tag":"cavalry","atk":5,"moveMult":1.14,"spdMult":1.056} },
        { id: "ranged_volley", name: "齊射訓練", rarity: "uncommon", desc: "[遠程] 攻擊 +3.8；射程 +11", effect: {"tag":"ranged","atk":4,"attackRange":11} },
        { id: "assassin_edge", name: "刺客刃法", rarity: "epic", desc: "[刺客] 攻擊 +11；暴擊 +9%", effect: {"tag":"assassin","atk":11,"critChance":0.09} },
        { id: "guard_manual", name: "守衛手冊", rarity: "uncommon", desc: "[坦克] 防禦 +3.8；HP +14", effect: {"tag":"tank","def":4,"hp":14} },
        { id: "boss_slayer", name: "屠龍者", rarity: "rare", desc: "對 Boss 傷害 +10%", effect: {"bossDmg":1.105} },
        { id: "tactical_retreat", name: "戰術撤退", rarity: "epic", desc: "非 Boss 戰敗時可撤退：保留 30% 金幣並繼續遠征（該房視為通過，無戰利品）", effect: {"keepGold":0.3} },
        { id: "war_doctrine", name: "戰爭教義", rarity: "epic", desc: "全隊攻擊 +4.5；全隊 HP +14", effect: {"atkAll":5,"hpAll":14} },
        { id: "legend_march", name: "傳奇行軍", rarity: "legendary", desc: "全隊攻擊 +7.5；全隊防禦 +3；戰後額外 +11 金幣", effect: {"atkAll":8,"defAll":3,"healAfter":11} },
        { id: "dominion", name: "霸權", rarity: "unique", desc: "全隊攻擊 +14；全隊防禦 +7.5；全隊 HP +30", effect: {"atkAll":14,"defAll":8,"hpAll":30} },
        { id: "soul_bond", name: "魂契", rarity: "unique", desc: "全隊 HP +53；治療量 +35%；開場全隊獲得護盾 30", effect: {"hpAll":53,"healBoost":1.35,"startShield":30} },
        { id: "last_stand", name: "背水一戰", rarity: "unique", desc: "HP 低於 50% 時攻擊 +41%；戰敗可撤退並保留 41% 金幣（非 Boss）", effect: {"lowHpAtk":0.413,"keepGold":0.413} }
    ];

    const TACTIC_UPGRADES = [
        { id: "focus_extend", name: "集火延長", rarity: "uncommon", desc: "集火持續時間 +1 秒", effect: { focusDuration: 1 } },
        { id: "focus_power", name: "集火強化", rarity: "rare", desc: "集火期間傷害額外 +15%", effect: { focusDmgBonus: 0.15 } },
        { id: "hold_cleanse", name: "守陣淨化", rarity: "rare", desc: "發動守陣時清除友軍負面狀態", effect: { holdCleanse: true } },
        { id: "hold_iron", name: "鐵壁守陣", rarity: "uncommon", desc: "守陣期間受傷再減 10%", effect: { holdTakenMult: 0.9 } },
        { id: "allout_crit", name: "總攻必暴", rarity: "rare", desc: "總攻期間首次攻擊必暴擊", effect: { allOutFirstCrit: true } },
        { id: "allout_fury", name: "總攻狂瀾", rarity: "uncommon", desc: "總攻期間攻擊額外 +10%", effect: { allOutDmgBonus: 0.1 } },
        { id: "tactic_reserve", name: "戰術預備", rarity: "epic", desc: "每場戰鬥額外 +1 次戰術指令", effect: { tacticsCharges: 1 } }
    ];

    const SYNERGIES = [
        { id: "holy2", tag: "holy", count: 2, name: "聖光庇護", desc: "[神聖]×2：治療量 +40%", effect: { tag: "holy", healBoost: 1.4 } },
        { id: "holy3", tag: "holy", count: 3, name: "聖裁", desc: "[神聖]×3：神聖單位防禦 +10、HP +40", effect: { tag: "holy", def: 10, hp: 40 } },
        { id: "summon2", tag: "summon", count: 2, name: "喚靈陣", desc: "[召喚]×2：召喚上限 +1、冷卻 -15%", effect: { tag: "summon", summonMax: 1, skillCdMult: 0.85 } },
        { id: "melee3", tag: "melee", count: 3, name: "鋒線", desc: "[近戰]×3：近戰攻擊 +12、HP +25", effect: { tag: "melee", atk: 12, hp: 25 } },
        { id: "ranged3", tag: "ranged", count: 3, name: "齊射", desc: "[遠程]×3：遠程攻擊 +10、射程 +20", effect: { tag: "ranged", atk: 10, attackRange: 20 } },
        { id: "arcane2", tag: "arcane", count: 2, name: "奧術共鳴", desc: "[奧術]×2：技能威力 +30%", effect: { tag: "arcane", skillPower: 1.3 } },
        { id: "fire2", tag: "fire", count: 2, name: "燃焰", desc: "[火焰]×2：攻擊 +8、技能威力 +20%", effect: { tag: "fire", atk: 8, skillPower: 1.2 } },
        { id: "tank2", tag: "tank", count: 2, name: "鐵壁", desc: "[坦克]×2：坦克 HP +50、防禦 +8", effect: { tag: "tank", hp: 50, def: 8 } },
        { id: "shadow2", tag: "shadow", count: 2, name: "影襲", desc: "[暗影]×2：攻速 +15%、暴擊 +10%", effect: { tag: "shadow", spdMult: 1.15, critChance: 0.1 } },
        { id: "beast2", tag: "beast", count: 2, name: "獸群", desc: "[野獸]×2：野獸攻擊 +14、移速感（攻速 +10%）", effect: { tag: "beast", atk: 14, spdMult: 1.1 } },
        { id: "mechanical2", tag: "mechanical", count: 2, name: "齒輪陣", desc: "[機械]×2：機械防禦 +8、HP +40", effect: { tag: "mechanical", def: 8, hp: 40 } },
        { id: "guard2", tag: "guard", count: 2, name: "衛隊", desc: "[護衛]×2：護衛 HP +45、防禦 +6", effect: { tag: "guard", hp: 45, def: 6 } },
        { id: "frenzy2", tag: "frenzy", count: 2, name: "狂潮", desc: "[狂戰]×2：狂戰攻擊 +16、攻速 +12%", effect: { tag: "frenzy", atk: 16, spdMult: 1.12 } },
        { id: "assassin2", tag: "assassin", count: 2, name: "暗殺網", desc: "[刺客]×2：刺客暴擊 +12%、攻速 +10%", effect: { tag: "assassin", critChance: 0.12, spdMult: 1.1 } },
        { id: "elite2", tag: "elite", count: 2, name: "菁英連", desc: "[精英]×2：精英攻擊 +12、HP +50", effect: { tag: "elite", atk: 12, hp: 50 } },
        { id: "cavalry2", tag: "cavalry", count: 2, name: "騎槍陣", desc: "[騎兵]×2：騎兵攻擊 +10、移速 +25%、攻速 +12%", effect: { tag: "cavalry", atk: 10, moveMult: 1.25, spdMult: 1.12 } },
        { id: "warrior3", tag: "warrior", count: 3, name: "戰團", desc: "[戰士]×3：戰士攻擊 +14、HP +30", effect: { tag: "warrior", atk: 14, hp: 30 } },
        { id: "ranger3", tag: "ranger", count: 3, name: "弓陣", desc: "[射手]×3：射手攻擊 +12、射程 +18", effect: { tag: "ranger", atk: 12, attackRange: 18 } },
        { id: "support2", tag: "support", count: 2, name: "援護網", desc: "[輔助]×2：治療量 +25%、輔助 HP +30", effect: { tag: "support", healBoost: 1.25, hp: 30 } }
    ];

    const TACTICS = [
        { id: "focus_fire", name: "集火", desc: "3 秒內友軍優先攻擊血量最低的敵人，傷害 +20%", duration: 3, charges: 1 },
        { id: "hold_line", name: "守陣", desc: "4 秒內友軍移速 -50%、防禦 +12、受傷 -15%", duration: 4, charges: 1 },
        { id: "all_out", name: "總攻", desc: "3 秒內友軍攻擊 +30%、移速 +25%", duration: 3, charges: 1 }
    ];
    global.WarDataParts.ARTIFACTS = ARTIFACTS;
    global.WarDataParts.ABILITIES = ABILITIES;
    global.WarDataParts.SYNERGIES = SYNERGIES;
    global.WarDataParts.TACTIC_UPGRADES = TACTIC_UPGRADES;
    global.WarDataParts.TACTICS = TACTICS;
})(typeof window !== "undefined" ? window : globalThis);
